node_exporter_version: "1.8.1"
node_exporter_user: "nodeusr"
node_exporter_group: "nodeusr"
node_exporter_install_dir: "/srv/node_exporter"
node_exporter_bin: "{{ node_exporter_install_dir }}/node_exporter"
node_exporter_port: 9100

