---
- name: Create node_exporter user
  user:
    name: nodeusr
    system: yes
    shell: /usr/sbin/nologin
    create_home: no

- name: Create directory
  file:
    path: /srv/node_exporter
    state: directory
    owner: nodeusr
    group: nodeusr

- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz
    mode: "0644"

- name: Extract Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /srv/node_exporter
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: nodeusr
    group: nodeusr

- name: Deploy systemd unit
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start node_exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes

