---
- name: Create prometheus user
  user:
    name: prometheus_usr
    system: yes
    shell: /usr/sbin/nologin
    create_home: no

- name: Create directories
  file:
    path: "/srv/prometheus/{{ item }}"
    state: directory
    owner: prometheus_usr
    group: prometheus_usr
  loop:
    - ""
    - data

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.54.0/prometheus-2.54.0.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /srv/prometheus
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: prometheus_usr
    group: prometheus_usr

- name: Deploy Prometheus config
  template:
    src: prometheus.yml.j2
    dest: /srv/prometheus/prometheus.yml
    owner: prometheus_usr
    group: prometheus_usr
    mode: "0644"

- name: Deploy systemd unit
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes

