---
- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Configure timezone
  timezone:
    name: "{{ timezone  }}"

- name: Enable and start NPT
  block:
    - name: installed
      package:
        name: systemd-timesyncd
        state: present

- name: enable NTP
  command: timedatectl set-ntp true
  changed_when: false

- name: start systemd-timesyncd
  service:
    name: systemd-timesyncd
    state: started
    enabled: yes


- name: update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Dedian"
# when добавлен для, доработки в будующем под новый inventory
